### ISSUE TITLE
Add accepted names to Smith and Brown tree for species in PAM

### ISSUE THREAD

**Issue by cjgrady** [biotaphy/projects#9]
Make sure to use the same name resolution method for tree as for occurrences

**Comment by cjgrady** [comment]
I am pulling names from both Open Tree and GBIF.  Since we have some time waiting on the models this will let us compare the two name resolution services to see what differences there are between them.

**Comment by cjgrady** [comment]
I pulled names from both the GBIF and Open Tree name resolution services and have the following results...

Of the 403,521 names in the tree combined with those from the occurrence data (bigger than the tree due to different synonyms in each, different spellings, with and without author, etc):

324,768 match to the same name in both GBIF and Open Tree
71,495 are different between the two
6992 are only found in GBIF
227 are only found in Open Tree

These differences aren’t trivial obviously and require some decisions for how to resolve them.  I think it is okay to use the GBIF names where there is only a match in GBIF and Open Tree names where there is only a match in Open Tree but then we need to decide what to do when both match but the responses are different.  For that scenario, I am inclined to prefer the GBIF names as I think their resolution service is a little more robust, or at least the way that I am using it is.  I am not as confident in the Open Tree service because I have to pull out author information when I search so it may just be guessing (or I may just be picking the wrong responses when it sends back a group of options, so the limitation may be that I am not retaining the author information to select the best result from the response).  The other big reason to use GBIF is that a majority of the specimen records came from GBIF and presumably will not need to have their name updated.

**Comment by ryanafolk** [comment]
I think I will follow your intuition here. I’m guessing GBIF is a bit more curated. Hopefully the greatly reduced number of GBIF look-ups will help.

**Comment by cjgrady** [comment]
Sounds good.  I think this is something we can explore more later though.

**Comment by cjgrady** [comment]
Updated names by matching in GBIF first and falling back to Open Tree if name wasn't found.  I then subset the tree to only those tips that were found and only the first time they were found in the tree.  So if two tip names resolved to the same accepted name, I only kept the first one.
